name: PR Comment Trigger

on:
    issue_comment:
        types: [created]

jobs:
    check_pr_comment:
        runs-on: ubuntu-latest
        if: github.event.issue.pull_request
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Run Action
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                COMMENT_BODY="${{github.event.comment.body}}"
                COMMENT_URL="${{github.event.comment.html_url}}"
                PR_URL="${{github.event.issue.pull_request.url}}"

            - name: send response to backend
              run: |
                const payload = {
                    comment_body: COMMENT_BODY,
                    comment_url: COMMENT_URL,
                    pr_url: PR_URL
                }
                const response = await fetch('https://008vv400-3000.inc1.devtunnels.ms/api/actions/pr',{
                    method: 'POST',
                    headers:{
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify(payload)
                })
                if(!response.ok){
                    throw new Error('Failed to send response to backend')
                }

